whiteowl:
  data-provider:
    kite:
      username: Kr8iquq+IQuUtHhn1xMeIQ==
      # Dark@Horse3
      password: gH5xVw9QCiNY6tjn8LXTNA==
      # 3DA57RQMUXVOBKT5E5OM75CS5RZXPXWT
      pin: UEpcbpBgOo1X4NpRYrRohKztpp7dPI7ZGTCsemRanCJVSwDtU69sTU8kZMOL10Ku
      
spring:
  h2:
    console:
      enabled: true
      path: /h2
  main:
    banner-mode: off
    log-startup-info: false
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    #url: jdbc:h2:mem:whiteowl
    url: jdbc:h2:~/.whiteowl/database/h2
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 20