whiteowl:
  data-provider:
    kite:
      username: Kr8iquq+IQuUtHhn1xMeIQ==
      password: StYLdA7W+uC4BRHDt2idyQ==
      pin: cjDp7WCtTW1lcKntKNivqnvYAol9u7aWkhQ22DbL/ONVSwDtU69sTU8kZMOL10Ku
      
spring:
  h2:
    console:
      enabled: true
      path: /h2
  main:
    banner-mode: off
    log-startup-info: false
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    #url: jdbc:h2:mem:whiteowl
    url: jdbc:h2:~/.whiteowl/database/h2
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 20