package com.whiteowl.core.position;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import javax.validation.Valid;

import org.ta4j.core.Trade.TradeType;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;
import com.whiteowl.core.trade.Trade;
import com.whiteowl.core.trade.TradeStatus;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@DynamoDBTable(tableName = "position")
@EqualsAndHashCode(of = {"id", "scripCode", "portfolioId", "type", "tradingStrategyConfigId"})
public class Position {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	
	@DynamoDBAttribute
	private String scripCode;
	
	@DynamoDBAttribute
	private String portfolioId;
	
	@DynamoDBTypeConvertedEnum
	private TradeType type;
	
	@DynamoDBTypeConvertedEnum
	private PositionStatus status;
	
	@DynamoDBAttribute
	private String tradingStrategyConfigId;
	
	@DynamoDBAttribute
	private List<@Valid Trade> entryTrades = new ArrayList<>();
	
	@DynamoDBAttribute
	private List<@Valid Trade> exitTrades = new ArrayList<>();
	
	public Position withPortfolioId(String portfolioId) {
		final Position position = new Position();
		position.setType(type);
		position.setStatus(status);
		position.setScripCode(scripCode);
		position.setPortfolioId(portfolioId);
		position.setTradingStrategyConfigId(tradingStrategyConfigId);
		entryTrades.stream().map(Trade::clone).forEach(position.getEntryTrades()::add);
		exitTrades.stream().map(Trade::clone).forEach(position.getExitTrades()::add);
		return position;
	}
	public int getEntryQuantity() {
		return entryTrades.stream()
				.filter(trade -> TradeStatus.COMPLETE.equals(trade.getStatus()))
				.collect(Collectors.summingInt(Trade::getQuantity));
	}
	
	public int getExitQuantity() {
		return exitTrades.stream()
				.filter(trade -> TradeStatus.COMPLETE.equals(trade.getStatus()))
				.collect(Collectors.summingInt(Trade::getQuantity));
	}
	
	public double getAverageEntryPrice() {
		return entryTrades.stream()
				.filter(trade -> TradeStatus.COMPLETE.equals(trade.getStatus()))
				.collect(Collectors.averagingDouble(Trade::getAveragePrice));
	}
	
	public double getAverageExitPrice() {
		return exitTrades.stream()
				.filter(trade -> TradeStatus.COMPLETE.equals(trade.getStatus()))
				.collect(Collectors.averagingDouble(Trade::getAveragePrice));
	}
	
	public double getEntryAmount() {
		return entryTrades.stream()
				.filter(trade -> TradeStatus.COMPLETE.equals(trade.getStatus()))
				.map(trade -> trade.getQuantity() * trade.getAveragePrice())
				.collect(Collectors.summingDouble(Double::doubleValue));
	}
	
	public double getExitAmount() {
		return exitTrades.stream()
				.filter(trade -> TradeStatus.COMPLETE.equals(trade.getStatus()))
				.map(trade -> trade.getQuantity() * trade.getAveragePrice())
				.collect(Collectors.summingDouble(Double::doubleValue));
	}
	
}
