package com.whiteowl.core.backtest.algotest.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import com.whiteowl.core.backtest.algotest.model.enums.EntryType;
import com.whiteowl.core.backtest.algotest.model.enums.ExpiryType;
import com.whiteowl.core.backtest.algotest.model.enums.LegTgtSLType;
import com.whiteowl.core.backtest.algotest.model.enums.LegType;
import com.whiteowl.core.backtest.algotest.model.enums.LotType;
import com.whiteowl.core.backtest.algotest.model.enums.MomentumType;
import com.whiteowl.core.backtest.algotest.model.enums.PositionType;
import com.whiteowl.core.backtest.algotest.model.enums.ReentryType;
import com.whiteowl.core.backtest.algotest.model.enums.StrikeType;
import com.whiteowl.core.backtest.algotest.model.enums.TrailStopLossType;
import lombok.Data;

import java.security.SecureRandom;

/**
 * One leg of the strategy (a single option/future/cash position rule).
 * {@code StrikeParameter} is polymorphic: a "StrikeType.*" string when
 * {@code EntryType} is strike-type based, otherwise a number (exact strike,
 * delta, premium, straddle price...) or an object for range-based entries.
 */
@Data
@JsonNaming(PropertyNamingStrategies.UpperCamelCaseStrategy.class)
@JsonInclude(JsonInclude.Include.ALWAYS)
public class LegConfig {

    private static final SecureRandom RANDOM = new SecureRandom();
    private static final String ID_ALPHABET = "abcdefghijklmnopqrstuvwxyz0123456789";

    /** Random 8-char leg id generated by the AlgoTest UI, e.g. "3i0g4xdi". */
    @JsonProperty("id")
    private String id = randomId();

    private PositionType positionType = PositionType.SELL;

    /** Lot sizing: LotType.Quantity (number of lots) or LotType.Capital. */
    private TypedValue lotConfig = TypedValue.of(LotType.QUANTITY, 1);

    private TypedValue legStopLoss = TypedValue.none();
    private TypedValue legTarget = TypedValue.none();

    /** TrailStopLossType + {@link TrailValue}, or disabled. */
    private TypedValue legTrailSL = TypedValue.noneObject();

    /** MomentumType + value, or disabled. */
    private TypedValue legMomentum = TypedValue.none();

    private ExpiryType expiryKind = ExpiryType.WEEKLY;
    private EntryType entryType = EntryType.ENTRY_BY_STRIKE_TYPE;

    /** {@link StrikeType} api value, number, or object — depends on {@link #entryType}. */
    private Object strikeParameter = StrikeType.ATM.getApiValue();

    private LegType instrumentKind = LegType.CE;

    /** ReentryType + {@link ReentryValue}, or disabled. */
    private TypedValue legReentrySL = TypedValue.noneObject();
    private TypedValue legReentryTP = TypedValue.noneObject();

    public static String randomId() {
        StringBuilder sb = new StringBuilder(8);
        for (int i = 0; i < 8; i++) {
            sb.append(ID_ALPHABET.charAt(RANDOM.nextInt(ID_ALPHABET.length())));
        }
        return sb.toString();
    }

    public void setStopLoss(LegTgtSLType type, double value) {
        legStopLoss = TypedValue.of(type, value);
    }

    public void setTarget(LegTgtSLType type, double value) {
        legTarget = TypedValue.of(type, value);
    }

    public void setTrailSL(TrailStopLossType type, double instrumentMove, double stopLossMove) {
        legTrailSL = TypedValue.of(type, new TrailValue(instrumentMove, stopLossMove));
    }

    public void setMomentum(MomentumType type, double value) {
        legMomentum = TypedValue.of(type, value);
    }

    public void setLots(LotType type, double value) {
        lotConfig = TypedValue.of(type, value);
    }

    public void setStrike(StrikeType strikeType) {
        entryType = EntryType.ENTRY_BY_STRIKE_TYPE;
        strikeParameter = strikeType.getApiValue();
    }

    /** "Closest Premium" entry — StrikeParameter is the target premium (number). */
    public void setClosestPremium(double premium) {
        entryType = EntryType.ENTRY_BY_PREMIUM;
        strikeParameter(premium);
    }

    /** Numeric StrikeParameter for delta/premium/exact-strike style entries. */
    public void strikeParameter(double value) {
        // store integral values as int so the wire shows 175, not 175.0
        strikeParameter = value == Math.rint(value) ? (Number) (int) value : (Number) value;
    }

    public void setReentryOnSL(ReentryType type, int count) {
        legReentrySL = TypedValue.of(type, new ReentryValue(count, null));
    }

    public void setReentryOnTP(ReentryType type, int count) {
        legReentryTP = TypedValue.of(type, new ReentryValue(count, null));
    }
}
