package com.whiteowl.core.portfolio;

import javax.validation.Valid;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.PositiveOrZero;
import javax.validation.constraints.Size;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;
import com.whiteowl.core.broker.Broker;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "portfolio")
public class Portfolio {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	
	@NonNull
	@NotBlank
	@Size(min = 3, max = 255)
	private String name;

	@NonNull
	@NotNull
	@Builder.Default
	@DynamoDBTypeConvertedEnum
	private Broker broker = Broker.CONSOLE;

	@Valid
	@NonNull
	@NotNull
	@Builder.Default
	@DynamoDBAttribute
	private Credentials credentials = new Credentials();

	public synchronized Credentials getCredentials() {
		return credentials == null ? credentials = new Credentials() : credentials;
	}

	@PositiveOrZero
	private double maxTradableAmount;

}
